### PR TITLE
Updated to use pipenv

### PR DESCRIPTION
**Pull request by golan13**
Updated files to use Pipenv-
Updated bootstrap file to install pipenv
removed requirements.txt
added Pipfile and Pipfile.lock
added section in contribution.md file about how to add new libraries

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
CI is broken

**Comment by golan13** [comment]
#59 is meant to fix the CI for all PRs. Waiting for it to be merged

**Review by mosesnagar — COMMENTED** [review]
Think after `rebase` it will be OK.

**Comment by golan13** [comment]
CI is fixed. Ready to merge

**Review by lioramilbaum — APPROVED** [review]

**Pull request merged**
