### PR TITLE
Login

### PR DESCRIPTION
**Pull request by golan13**
To be merged only after #65 is merged.
Added user login functionality
Added test for user login

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
Verify the tests are running in CI before requesting a review

**Review by mosesnagar — COMMENTED** [review]
I think its good, but add `# noqa` comment when you import routes on tests.

**Comment by golan13** [comment]
> I think its good, but add `# noqa` comment when you import routes on tests.

It still passes the tests, so why is that necessary?

**Comment by Michal-Shamir** [comment]
> > I think its good, but add `# noqa` comment when you import routes on tests.
> 
> It still passes the tests, so why is that necessary?

because the tests are changed in  #78 to check unused imports as well, it was not yet merged but once it does it will not pass

**Comment by golan13** [comment]
> > > I think its good, but add `# noqa` comment when you import routes on tests.
> > 
> > 
> > It still passes the tests, so why is that necessary?
> 
> because the tests are changed in #78 to check unused imports as well, it was not yet merged but once it does it will not pass
I see.
I'm sure there will be more things that fail the new CI PR. Will take care of all of them once it is merged.

**Review by ifireball — COMMENTED** [review]
Seeing this is marked as a draft. Is review requested ATM?

**Comment by golan13** [comment]
> Seeing this is marked as a draft. Is review requested ATM?

It is marked as a draft because we are waiting for the CI PR to be merged as Liora asked. Also, as mentioned in the description #65 must be merged before so I will change it from draft after it is merged. It is ready for review nevertheless so if you have time I will appreciate it.

**Pull request merged**
