### PR TITLE
Revert "configuring CI"

### PR DESCRIPTION
**Pull request by Michal-Shamir**
Reverts beyond-io/tutor#27
I'd like to add specific checks to flake8 since now it contains all the possible flake8 rules, and tests things that we don't want to check that make our commits fail. 

can't commit the changes to flake8 without reverting since it will fail as well

### CODE REVIEW

**Comment by yuvalmargules** [comment]
would let us merge other approved PRs

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
This is NOT a good practice to submit PRs from within the head repo. Use your fork for all code contributions.

**Comment by Michal-Shamir** [comment]
@lioramilbaum  the merge was done from my fork, but reverting a merge can be done only from the main repo if I'm not mistaken?

**Comment by lioramilbaum** [comment]
> @lioramilbaum the merge was done from my fork, but reverting a merge can be done only from the main repo if I'm not mistakenI

Is there a technical blocker to provide a revert commit over a PR originating from a fork? Have you updated your local/fork repos with the latest changes from head/upstream before trying to provide a revert commit?

**Pull request closed without merging**
