### PR TITLE
Register user

### PR DESCRIPTION
**Pull request by golan13**
Added ability to register user
Added Users table
Integrated with register controller to save user in db
Added tests for register user

### CODE REVIEW

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
1. CI is broken
2. There are no tests in this PR

**Review by Michal-Shamir — APPROVED** [review]

**Comment by lioramilbaum** [comment]
This PR requires a rebase

**Review by mosesnagar — APPROVED** [review]
I thinks it's OK. To make it more testable maybe you could move the all logic of hashing password to a new method on `User` class. So, on the controller you only pass the parameters and the method would do all the work, then you can test that process.

**Review by lioramilbaum — CHANGES_REQUESTED** [review]
The test was not executed in the CI

**Comment by golan13** [comment]
> The test was not executed in the CI

There is a different PR #75  for that.

**Comment by lioramilbaum** [comment]
> > The test was not executed in the CI
> > @lioramilbaum
> > There is a different PR #75  for that.

Then lets wait for #75 to land and than re-run the CI for this PR

**Comment by bardielle** [comment]
@golan13 is this PR still relevant?

**Comment by golan13** [comment]
> @golan13 is this PR still relevant? 

@bardielle of course

**Pull request merged**
