### PR TITLE
Added Flask-based web-site for Tutor: The program flasksite.py routes for Home and About html pages, which are both using templates for code reuse

### PR DESCRIPTION
**Pull request by LiorRey**
- Assets folder:
 * Tutor Logo.docx for editing Tutor's logo
 * Tutor Logo.png

### CODE REVIEW

**Review by igoihman — CHANGES_REQUESTED** [review]
The PR name is not descriptive enough

**Comment by LiorRey** [comment]
Hey Irit,

I've added some things to the repo now. Is the PR name is now descriptive enough?

Thank you.

**Comment by ifireball** [comment]
@LiorRey , @mosesnagar - this PR seems to have duplicates with things I see in PR #7 - which one should we review and merge? Are you communicating within your team?

**Comment by mosesnagar** [comment]
No need.

**Pull request closed without merging**
