### PR TITLE
improve tests

### LINKED ISSUE #96: improve tests
need to add fixtures and functions for tests to make more readable and less repetitive code
create config files for tests

### PR DESCRIPTION
**Pull request by golan13**
Added pytest fixture for client
Added cleanup process to empty db after running all tests
Added helper functions for tests to make cleaner and more readable code

### CODE REVIEW

**Review by mosesnagar — COMMENTED** [review]
Maybe you can export the dummy data into one file, so we will import the dicts we want. 
For example, instead of writing 
```
register_user = {
        'username': 'test',
        'email': 'test@email.com',
        'password': '123',
        'confirm_password': '123',
        'submit': 'Sign Up'
    }
```
in 3 different files, one file can hold that dict and the other can import it. That way, we can just change the scheme on one file when needed.

**Review by mosesnagar — APPROVED** [review]

**Comment by golan13** [comment]
> Maybe you can export the dummy data into one file, so we will import the dicts we want.
> For example, instead of writing
> 
> ```
> register_user = {
>         'username': 'test',
>         'email': 'test@email.com',
>         'password': '123',
>         'confirm_password': '123',
>         'submit': 'Sign Up'
>     }
> ```
> 
> in 3 different files, one file can hold that dict and the other can import it. That way, we can just change the scheme on one file when needed.

I converted it to draft. Still working on it.
I was thinking about adding a functions file with functions to create the dummy data for testing. will request a review when finished.

**Review by yuvalmargules — APPROVED** [review]

**Comment by golan13** [comment]
Added helper function to register and login user

**Review by mosesnagar — COMMENTED** [review]
The main issue here is the `tests/functions.py` file. If you and I want to add a new PRs with tests, so both of us should update that file - so we will have a conflict to resolve.
Also, the more tests we have, the long this file will be.

**Comment by golan13** [comment]
> The main issue here is the `tests/functions.py` file. If you and I want to add a new PRs with tests, so both of us should update that file - so we will have a conflict to resolve.
> Also, the more tests we have, the long this file will be.

They are helper functions for the test that we will probably keep using for other tests that come up. I'm not sure I understand why its an issue.

**Comment by mosesnagar** [comment]
> > The main issue here is the `tests/functions.py` file. If you and I want to add a new PRs with tests, so both of us should update that file - so we will have a conflict to resolve.
> > Also, the more tests we have, the long this file will be.
> 
> They are helper functions for the test that we will probably keep using for other tests that come up. I'm not sure I understand why its an issue.

Because we will not only use that file, we also will maintain it and add new functions to use in other tests, even if both of them not related at all.
For example, if you would write a PR about favorites courses and I would write one about editing a resource - both of all would add a new functions to `tests/functions.py` - even our PRs not related at all - and will have a conflict to resolve.

**Comment by golan13** [comment]
> > > The main issue here is the `tests/functions.py` file. If you and I want to add a new PRs with tests, so both of us should update that file - so we will have a conflict to resolve.
> > > Also, the more tests we have, the long this file will be.
> > 
> > 
> > They are helper functions for the test that we will probably keep using for other tests that come up. I'm not sure I understand why its an issue.
> 
> Because we will not only use that file, we also will maintain it and add new functions to use in other tests, even if both of them not related at all.
> For example, if you would write a PR about favorites courses and I would write one about editing a resource - both of all would add a new functions to `tests/functions.py` - even our PRs not related at all - and will have a conflict to resolve.

So how do you suggest we should do it?

**Comment by mosesnagar** [comment]
> > > > The main issue here is the `tests/functions.py` file. If you and I want to add a new PRs with tests, so both of us should update that file - so we will have a conflict to resolve.
> > > > Also, the more tests we have, the long this file will be.
> > > 
> > > 
> > > They are helper functions for the test that we will probably keep using for other tests that come up. I'm not sure I understand why its an issue.
> > 
> > 
> > Because we will not only use that file, we also will maintain it and add new functions to use in other tests, even if both of them not related at all.
> > For example, if you would write a PR about favorites courses and I would write one about editing a resource - both of all would add a new functions to `tests/functions.py` - even our PRs not related at all - and will have a conflict to resolve.
> 
> So how do you suggest we should do it?

Really not sure, what do you think about splitting the functions to files by relation? Like all the login and register function in one, file and etc. I think it will reduce the conflicts.

**Review by LiorRey — APPROVED** [review]

**Review by Michal-Shamir — APPROVED** [review]

**Pull request merged**
